### ISSUE TITLE
curl not working with  --no-progress-meter

### ISSUE THREAD

**Issue by sagarnikale** [SUSE-Enceladus/cloud-netconfig#33]
after latest update curl command has new switch  --no-progress-meter.
Cloud-netcofig script is not working becaus eof this switch.

curl: option --no-progress-meter: is unknown

issue is resolved after removing the switch or correcting it to --no-progress-bar

**Comment by jgleissner** [comment]
Hi, which curl version are you using? The parameter was added with curl 7.67.0.
